attempt just up to download step

diff --git a/.github/workflows/r4ss-extra-tests-3.24.yml b/.github/workflows/r4ss-extra-tests-3.24.yml
--- a/.github/workflows/r4ss-extra-tests-3.24.yml
+++ b/.github/workflows/r4ss-extra-tests-3.24.yml
@@ -73,42 +73,40 @@ jobs:
           ls -l
           chmod a+x ss3*
           mv ss3* inst/extdata/simple_3.24/ss3
-          # sudo chmod a+x ss3
-          # mv ss3 inst/extdata/simple_3.24/ss3
         
-      - name: Test coverage
-        run: |
-          cov <- covr::package_coverage(
-            type = c("none"),
-            code = c(
-              "library(testthat)",
-              'test_file("tests/testthat/test-older_ss3.R")'
-            ),
-            quiet = FALSE,
-            clean = FALSE,
-            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
-          )
-          covr::to_cobertura(cov)
-        shell: Rscript {0}
-      
-      - uses: codecov/codecov-action@v4
-        with:
-          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
-          file: ./cobertura.xml
-          plugin: noop
-          disable_search: true
-          token: ${{ secrets.CODECOV_TOKEN }}
-  
-      - name: Show testthat output
-        if: always()
-        run: |
-          ## --------------------------------------------------------------------
-          find '${{ runner.temp }}/r4ss' -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
-  
-      - name: Upload test results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-test-failures
-          path: ${{ runner.temp }}/r4ss
+      # - name: Test coverage
+      #   run: |
+      #     cov <- covr::package_coverage(
+      #       type = c("none"),
+      #       code = c(
+      #         "library(testthat)",
+      #         'test_file("tests/testthat/test-older_ss3.R")'
+      #       ),
+      #       quiet = FALSE,
+      #       clean = FALSE,
+      #       install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
+      #     )
+      #     covr::to_cobertura(cov)
+      #   shell: Rscript {0}
+      # 
+      # - uses: codecov/codecov-action@v4
+      #   with:
+      #     fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
+      #     file: ./cobertura.xml
+      #     plugin: noop
+      #     disable_search: true
+      #     token: ${{ secrets.CODECOV_TOKEN }}
+      # 
+      # - name: Show testthat output
+      #   if: always()
+      #   run: |
+      #     ## --------------------------------------------------------------------
+      #     find '${{ runner.temp }}/r4ss' -name 'testthat.Rout*' -exec cat '{}' \; || true
+      #   shell: bash
+      # 
+      # - name: Upload test results
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: coverage-test-failures
+      #     path: ${{ runner.temp }}/r4ss
